app/login/models.py
from werkzeug.security import check_password_hash
from app import get_db_connection, login_manager

@login_manager.user_loader
def load_user(username):
    return User(username)

class User(object):
    def __init__(self, username = None):
        self.username  = None
        self.password_hash = None
        self.is_active = False
        self.is_authenticated = True
        self.account_type = None

        if username:
            self.username = username
            self.__load_user()


    def __load_user(self):
        connection = get_db_connection()

        try:
            with connection.cursor() as cursor:
                sql = 'SELECT username, password, isActive, accountType FROM account WHERE username=%s'
                cursor.execute(sql, self.username)

                result = cursor.fetchone()
                if result:
                    self.username, self.password_hash, self.is_active, self.account_type = result
                else:
                    self.username = None

        finally:
            connection.close()


    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


    def get_id(self):
        return self.username

app/login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
import os, pymysql, sys
from getpass import getpass
from config import Config
from flask import Blueprint, Flask, redirect, render_template, request, url_for
from flask_login import LoginManager, current_user

app = Flask(__name__)
app.config.from_object(Config)
app.config['DB_PASSWORD'] = getpass(prompt='DB Password: ')

def get_db_connection():
    host = app.config['DB_HOST']
    user = app.config['DB_USER']
    password = app.config['DB_PASSWORD']
    database = app.config['DATABASE']

    return pymysql.connect(host=host, user=user, password=password, database=database)

try:
    get_db_connection()

except Exception as e:
    if str(e.args[0]) == '1045':
        print('Incorrest password.')
    elif str(e.args[0]) == '2003':
        print('Connection refused on `localhost`. Please make sure the MySQL Server is running.')
    else:
        print('Unable to connect to DB: unknown error', e)
    sys.exit()

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login.login'

indexbp = Blueprint('index', __name__, template_folder='templates')

@indexbp.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('index.home'))

    return redirect(url_for('login.login'))


@indexbp.route('/home')
def home():
    return render_template('home.html')


@indexbp.route('/about')
def about():
    return render_template('about.html')


@indexbp.route('/archive')
def archive():
    return render_template('archive.html')


@indexbp.route('/attendance')
def attendance():
    return render_template('attendance.html')


@indexbp.route('/create')
def create():
    return render_template('create.html')


@indexbp.route('/reports')
def reports():
    return redirect(url_for('reports.index'))


@indexbp.route('/support')
def support():
    return render_template('support.html')

@indexbp.route('/pending')
def pending():
    return redirect(url_for('pending.index'))



from app.views import *

app/accounts/controllers.py
from app.accounts.services import create_account
from app.positions.services import get_position_list, get_section_division_list
from flask import Blueprint, render_template, request
from json import dumps

accountsbp = Blueprint('accounts', __name__, template_folder='templates')

@accountsbp.route('/accounts')
def accounts():
    positions = get_position_list()
    section_divisions = get_section_division_list()

    return render_template('accounts.html', positions=positions, section_divisions=section_divisions)


@accountsbp.route('/accounts/create', methods=['POST'])
def create():
    data = {
        'username': request.form['username'],
        'password': request.form['password'],
        'first_name': request.form['first-name'],
        'middle_initial': request.form['middle-initial'],
        'last_name': request.form['last-name'],
        'active': True if 'active' in request.form.keys() else False,
        'account_type': request.form['account-type']
    }
    
    if request.form['account-type'] == 'Employee':
        data['position'] = request.form['position']
        data['contact_number'] = request.form['contact-number']
        data['is_working_sun'] = True if 'is-working-sun' in request.form.keys() else False
        data['is_working_mon'] = True if 'is-working-mon' in request.form.keys() else False
        data['is_working_tue'] = True if 'is-working-tue' in request.form.keys() else False
        data['is_working_wed'] = True if 'is-working-wed' in request.form.keys() else False
        data['is_working_thu'] = True if 'is-working-thu' in request.form.keys() else False
        data['is_working_fri'] = True if 'is-working-fri' in request.form.keys() else False
        data['is_working_sat'] = True if 'is-working-sat' in request.form.keys() else False

    else:
        data['section_division'] = request.form['section-division']

    message = create_account(data)
    

    return dumps({'status': message})

app/create/controllers.py
from flask import Blueprint, render_template, request, url_for
from datetime import datetime
from app.profile.models import Employee
from app.create.services import create_task, create_report, create_taskInstance, create_weeklyEntry
from flask_login import current_user
from json import dumps

createbp = Blueprint('create', __name__, template_folder='templates')


# profile = Employee(current_user.username)


# @createbp.route('create')
# def create():
#   return render_template('create.html')

@createbp.route('/')
def index():
  return render_template('create.html')

@createbp.route('/task_post', methods=['POST'])
def task_post():
  profile = None



  profile = Employee(current_user.username)
  data = request.get_json()



  taskData = {
    'taskDescription': data['name'],
    'isRecurring': bool(data['isRecurring']),
    'hasQuantity': bool(data['hasQuantity']),
    'accountId': profile.id,
    'employeePosition': profile.position_id
  }


  weekId = create_task(taskData)


  return 'task added.'


@createbp.route('/submit', methods=['POST'])
def submit():

  profile = None

  profile = Employee(current_user.username)

  taskDict = {}

  i = 0

  data = request.get_json()
  tasks = data['tasks']
  submitData = data['data']
  period = data['period']
  weeks = data['weeks']

# task/s insert to db
  for task in tasks:
    taskData = {
    'taskDescription': task['name'],
    'isRecurring': bool(task['isRecurring']),
    'hasQuantity': bool(task['hasQuantity']),
    'accountId': profile.id,
    'employeePosition': profile.position_id
    }

    taskId = create_task(taskData)
    taskDict[i] = taskId
    i+= 1


# report insert to db
  reportData = {
    'employeeId': profile.employeeId,
    'periodId': period
  }

  reportId = create_report(reportData)

  entryIds = {}

  weekInstance = []

  for week in submitData:
    weekInstance.append(week['week'])

  weekInstance = list(set(weekInstance))


# weekly entry insert to db
  for instance in weekInstance:
    weekPeriod = weeks[instance]['week'].replace(',', '').replace('-', '')
    weekPeriod = weekPeriod.split(" ")

    if(len(weekPeriod) == 3):
      startDate = weekPeriod[0] + ' ' + weekPeriod[1] + ' ' + weekPeriod[2]
      startDate = stringToDate(startDate)
      weekData = {
      'startDate': startDate,
      'endDate': startDate,
      'reportId': reportId
      }
      entryIds[instance] = create_weeklyEntry(weekData)
    elif(len(weekPeriod) == 5):
      weekPeriod.remove('')
      startDate = weekPeriod[0] + ' ' + weekPeriod [1] + ' ' + weekPeriod[3]
      endDate = weekPeriod[0] + ' ' + weekPeriod [2] + ' ' + weekPeriod[3]
      weekData = {
      'startDate': stringToDate(startDate),
      'endDate':  stringToDate(endDate),
      'reportId': reportId
      }
      entryIds[instance] = create_weeklyEntry(weekData)
    elif(len(weekPeriod) == 6):
      weekPeriod.remove('')
      startDate = weekPeriod[0] + ' ' + weekPeriod[1] + ' ' + weekPeriod[4]
      endDate = weekPeriod[2] + ' ' + weekPeriod[3] + ' ' + weekPeriod[4]
      weekData = {
      'startDate': stringToDate(startDate),
      'endDate':  stringToDate(endDate),
      'reportId': reportId
      }
      entryIds[instance] = create_weeklyEntry(weekData)

  for instance in submitData:
    instanceData = {
      'taskId': taskDict[instance['task_id']],
      'week': entryIds[instance['week']],
      'reportId': reportId
    }
    create_taskInstance(instanceData)

  return dumps({'redirect': url_for('index.create')})


def stringToDate(str):
  return datetime.strptime(str, '%B %d %Y').date()

app/login/controllers.py
from app.login.forms import LoginForm
from app.login.models import User
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.urls import url_parse

loginbp = Blueprint('login', __name__, template_folder='templates')

@loginbp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))

    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        next_page = request.args.get('next')

        user = User(form.username.data)
        if user.username and user.check_password(form.password.data):
            login_user(user)

            if not next_page or url_parse(next_page).netloc != '':
                next_page = url_for('index.home')

        else:
            flash('Incorrect username/password.')
            next_page = request.referrer

        return redirect(next_page)

    return render_template('login.html', form=form)


@loginbp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('login.login'))

app/pending/controllers.py
from flask import Blueprint, render_template, request, url_for
from app.positions.services import get_position_list, get_section_division_list
from app.profile.models import Admin, Chief
from app.pending.services import *
from json import dumps
from flask_login import current_user
from datetime import datetime
import calendar



pendingbp = Blueprint('pending', __name__, template_folder='templates', url_prefix='/pending')
now = datetime.now()
year = now.year

@pendingbp.route('/')
def index():
  if current_user.account_type.lower() == 'employee':
    return render_template('home.html', message='Account type not permitted.')
  elif current_user.account_type.lower() == 'chief':
    profile = Chief(current_user.username)
    divisions = get_divisions(profile.divisionId)
  elif current_user.account_type.lower() == 'admin':
    divisions = get_all_divisions()

  for dv in divisions:
    positions = []
    positions = get_positions(dv['id'])
    dv['positions'] = positions
    for po in positions:
      periodIndex = []
      periods = []
      employees = get_employees_position(po['id'])
      for em in employees:
        reports = get_employee_reports(em['id'])
        for r in reports:
          periodIndex.append(r['period'])
      periodIndex = list(set(periodIndex))
      for p in periodIndex:
        period = period_to_object(p)
        periods.append(period)
      po['periods'] = periods
      for pr in periods:
        data = {
          'period': pr['id'],
          'position': po['id']
        }
        employees = get_employees_period(data)
        # pr['employees'] = employees
        pr['employees'] = employees
        for em in employees:
          data = {
            'employee': em['employeeId'],
            'period': pr['id']
          }
          em['firstName'] = em['firstName'].upper()
          em['lastName'] = em['lastName'].upper()
          reports =  get_reports_employee_pending(data)
          em['reports'] = reports
          for rp in reports:
            weeks = get_weeks_report(rp['id'])
            rp['weeks'] = weeks
            for w in weeks:
              w['weekName'] = get_week_name(w)
              data = {
                'week': w['id'],
                'report': rp['id']
              }
              tasks = get_tasks_week(data)
              w['tasks'] = tasks


  return render_template('pending.html', data=divisions)

@pendingbp.route('/approve', methods=['POST'])
def approve():

  data = request.get_json()

  reportId = data['reportId']

  print(reportId)
  status = approve_report(reportId)

  return dumps({'redirect': url_for('index.reports')})







def period_to_object(id):

  period = get_attendance_period(id)

  period['name'] = get_period_name(period)



  return period

def get_period_name(period):
  month1 = calendar.month_name[period['monthStart']]
  month2 = calendar.month_name[period['monthEnd']]
  day1 = str(period['dayStart'])
  day2 = str(period['dayEnd'])
  currentYear = str(year)

  date1 = month1 + " " + day1 + ", " + currentYear
  date2 = month2 + " " + day2  + ", " + currentYear

  name = date1 + ' - ' + date2
  return name

def get_week_name(w):
  date1 = datetime.strftime(w['dateStart'], '%B %d, %Y - ')
  date2 = datetime.strftime(w['dateEnd'], '%B %d, %Y')
  return date1 + date2

app/positions/controllers.py
from app.accounts.services import get_verifiers
from app.positions.services import check_position_duplicate
from app.positions.services import create_position, create_section_division
from app.positions.services import delete_position_record, delete_secdiv_record
from app.positions.services import get_section_divisions_and_positions, get_verifier
from app.positions.services import update_secdiv_record, update_position_record
from flask import Blueprint, render_template, request
from json import dumps

positionsbp = Blueprint('positions', __name__, template_folder='templates')

@positionsbp.route('/positions')
def positions():
    section_divisions = get_section_divisions_and_positions()
    verifiers = get_verifiers()

    return render_template('positions.html', section_divisions=section_divisions, verifiers=verifiers)


@positionsbp.route('/positions/new-position', methods=['POST'])
def new_position():
    data = {
        'title': request.form['position-title'],
        'section_division': request.form['section-division']
    }

    create_position(data)

    return dumps({'status': 'OK'})


@positionsbp.route('/positions/new-section-division', methods=['POST'])
def new_section_division():
    data = {
        'name': request.form['name'],
        'verifier': request.form['verifier']
    }

    create_section_division(data)

    return dumps({'status': 'OK'})


@positionsbp.route('/positions/get-verifier', methods=['GET'])
def get_sec_div_verifier():
    sec_div = request.args.get('section_division')
    verifier = get_verifier(sec_div)

    data = {
        'verifier': verifier
    }

    return dumps({'status': 'OK', 'data': data})


@positionsbp.route('/positions/delete-secdiv')
def delete_secdiv():
    sec_div = request.args.get('sec_div')
    delete_secdiv_record(sec_div)

    return dumps({'status': 'OK'})


@positionsbp.route('/positions/update-secdiv', methods=['POST'])
def update_secdiv():
    current = request.form['current_name']
    new = request.form['name']
    verifier = request.form['verifier']

    update_secdiv_record(current, new, verifier)
    
    return dumps({'status': 'OK'})


@positionsbp.route('/positions/update-pos', methods=['POST'])
def update_position():
    current = request.form['cur_pos']
    cur_secdiv = request.form['cur_secdiv']
    new = request.form['position']
    secdiv = request.form['secdiv']
    
    if current != new or cur_secdiv != secdiv:
        duplicate = check_position_duplicate(new, secdiv)

        if duplicate:
            return dumps({'status': 'FAILED: DUPLICATE ENTRY'})

    update_position_record(current, new, secdiv)
    return dumps({'status': 'OK'})


@positionsbp.route('/positions/delete-position')
def delete_position():
    pos = request.args.get('pos')
    sec_div = request.args.get('secdiv')

    delete_position_record(sec_div, pos)

    return dumps({'status': 'OK'})

app/profile/controllers.py
from app.positions.services import get_position_list, get_section_division_list
from app.profile.models import Admin, Chief, Employee
from flask import Blueprint, render_template
from flask_login import current_user

profilebp = Blueprint('profile', __name__, template_folder='templates')

@profilebp.route('/profile')
def profile():
    profile = None

    if current_user.account_type.lower() == 'admin':
        profile = Admin(current_user.username)
    elif current_user.account_type.lower() == 'chief':
        profile = Chief(current_user.username)
    else:
        profile = Employee(current_user.username)

    positions = get_position_list()
    sections_divisions = get_section_division_list()

    return render_template('my_profile.html', profile=profile, positions=positions, section_divisions=sections_divisions)

app/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    QC-EPWMD | Employee Accomplishment Report System
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <meta name="viewport" content="width=device-width" />

  <link rel="logo" sizes="76x76" href="{{ url_for('static', filename='img/logo.png') }}"" />
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/logo.png') }}"" />

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{{ url_for('static', filename='css/bootstrap4.min.css') }}" rel="stylesheet" />
  <link href="/static/css/now-ui-dashboard.css?v=1.3.0" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
<!-- Start of Sidebar -->
    <div class="sidebar" data-color="blue">
      <div class="logo">
        <a href="#" class="simple-text logo-mini">
          <img src="{{ url_for('static', filename='img/logo.png') }}">
        </a>
        <a href="#" class="simple-text logo-normal">
          <h6 class="system-name">EPWMD Employee <br>Accomplishment<br>Report System</h6>
        </a>
      </div>
      <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
          <li>
            <a href="{{ url_for('index.home') }}">
              <i class="now-ui-icons shopping_shop"></i>
              <p>Home</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('index.create') }}">
              <i class="now-ui-icons files_single-copy-04"></i>
              <p>Create New Report</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('index.pending') }}">
              <i class="now-ui-icons ui-1_bell-53"></i>
              <p>View Pending Reports</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('index.reports') }}">
              <i class="now-ui-icons files_box"></i>
              <p>View Reports</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('accounts.accounts') }}">
              <i class="now-ui-icons users_circle-08"></i>
              <p>Manage Accounts</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('positions.positions') }}">
              <i class="now-ui-icons objects_globe"></i>
              <p>Manage Positions</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('index.archive') }}">
              <i class="now-ui-icons files_box"></i>
              <p>View Archive</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
<!-- End of Sidebar -->

    <div class="main-panel" id="main-panel">
<!-- Start of Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#about">About Us</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <!-- <form>
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                  </div>
                </div>
              </div>
            </form> -->
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="now-ui-icons ui-1_settings-gear-63"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Settings</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('profile.profile') }}">My Profile</a>
                  <a class="dropdown-item" href="{{ url_for('login.logout') }}">Logout</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
<!-- End Navbar -->

<!-- Start of Header -->
      <div class="panel-header panel-header-lg">
        <h5 id="header-title"><b>About the Team</b></h5>
        <p id="header-desc">Learn more about the team behind the system.</p>
      </div>
<!-- End of Header -->

<!-- Start of Content -->
      <div class="content">
        <div class="content-2">
          <div class="row">
            <div class="col-md-12">
              <div class="card card-chart">
                <div class="pull-center">
                  <div class="card-header ">
                    <br>
                    <h3 id="main-profile">REINE TECHNOLOGIES</h3>
                  </div>
                  <div class="card-body ">
                    <br>
                    <p><b>Sabine Jeanjaquet | Denille Legaspi | Camille Muli | Danica Palanca</b></p>
                    <p class="text-description">ReineTech is comprised of a group of students from the Ateneo de Manila University who took up BS Management Information Systems. In fulfillment of our thesis requirements, we designed and developed the Employee Accomplishment Report System for the Environmental Protection and Waste Management Department under the Quezon City Hall.</p>
                    <br>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<!-- End of Content -->

<!-- Start of Footer -->
      <footer class="footer">
        <div class="container-fluid">
          <nav>
            <ul>
              <li>
                <a href="{{ url_for('index.about') }}">
                  About Us
                </a>
              </li>
              <li>
                <a href="{{ url_for('index.support') }}">
                  Support
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright" id="copyright">
            &copy;
            <script>
            document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
            </script>, Design from
            <a href="https://www.invisionapp.com" target="_blank">Invision</a> & <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>. Developed by ReineTech.
          </div>
        </div>
      </footer>
<!-- End of Footer -->
    </div>
  </div>


  <!--   Core JS Files   -->
  <script src="{{ url_for('static', filename='js/core/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/core/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/core/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>
  <!--  Notifications Plugin    -->
  <script src="{{ url_for('static', filename='js/plugins/bootstrap-notify.js') }}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{{ url_for('static', filename='js/now-ui-dashboard.min.js?v=1.3.0') }}" type="text/javascript"></script>

</body>

</html>

app/templates/report_template.html
<HTML>
</HEAD>
<BODY LANG="en-PH" DIR="LTR">
<P STYLE="margin-bottom: 0in" ALIGN=CENTER><I><B>    Republic of the Philippines</B></I></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in"><I><B>Quezon City</B></I></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0in; border-top: none; border-bottom: 1.50pt solid #00000a; border-left: none; border-right: none; padding-top: 0in; padding-bottom: 0.01in; padding-left: 0in; padding-right: 0in">
<FONT COLOR="#2f5496"><FONT SIZE=3><B>ENVIRONMENT PROTECTION AND
WASTE MANAGEMENT DEPARTMENT</B></FONT></FONT></P>
</P>
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in"><FONT SIZE=3><B>ACCOMPLISHMENT
REPORT</B></FONT></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0in"><FONT SIZE=2>Attendance
Period: {{data.report.period.periodName}}</FONT></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in"><FONT SIZE=2>Payroll
Period: {{data.report.payroll.name}}</FONT></P>
<TABLE WIDTH=719 CELLPADDING=7 CELLSPACING=0>
  <COL WIDTH=174>
  <COL WIDTH=516>
  <TR VALIGN=TOP>
    <TD WIDTH=174 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
      <P ALIGN=CENTER><B>DATE</B></P>
    </TD>
    <TD WIDTH=516 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
      <P ALIGN=CENTER><B>TASK ACCOMPLISHED</B></P>
    </TD>
  </TR>
  {% for week in data.report.weeks %}
  <tr ROWSPAN={{week.taskCount}}>
    <td  WIDTH=174 STYLE="border: 1px solid #00000a; padding-top: 0.1in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
      <P ALIGN=CENTER>{{week.weekName}}</P>
    </td>
    <td STYLE="border: 1px solid #00000a; padding-top: 0.1in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in" VALIGN="bottom">
    <ol>
      {% for task in week.tasks %}
       <li>{{task.description}}</li>
      {% endfor %}
    </ol>
    </td>
  </tr>
  {% endfor %}
</TABLE>

<div bottom="10px">
  <br>
<P STYLE="margin-bottom: 0.11in"><B>Submitted by:</B></P>
<P STYLE="margin-bottom: 0.3in">
</P>
<P STYLE="margin-bottom: 0in"><U><B>{{data.report.lastName}}, {{data.report.firstName}} {{data.report.middleInitial}}</B></U></P>
<P STYLE="margin-bottom: 0.11in">Signature over Printed name</P>
<P STYLE="margin-bottom: 0.11in">
</P> <BR>
<P STYLE="margin-bottom: 0.11in">
</P>
<P STYLE="margin-bottom: 0in"><U><B>{{data.chief.lastName}}, {{data.chief.firstName}} {{data.chief.middleInitial}}.</B></U></P>
<P STYLE="margin-bottom: 0.11in">Acting Admin Officer</P>
<P STYLE="margin-top: 0.17in; margin-bottom: 0.11in"><B>Noted:</B></P>
</div>
</BODY>
</HTML>